name = "LividJava's Create Re-Stitched"
author = "LividJava"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "227a669ac2fab38c4a9734229b1492b2932b8f9c40bbbd7ea8e38a83db94679b"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0"
