name = "LividJava's Create Refabricated"
author = "LividJava"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0a747a8d2f3fd326406f6254af93208beb09f808a1f51f7601cc11c627cf5fc"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"
