name = "LividJava's Create Refabricated"
author = "LividJava"
version = "0.0.3-hotfix1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5e0200150b9f36b75a8a3982d984711379d724411e0789b3801a79598d435d3"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"
