name = "LividJava's Create Re-Stitched"
author = "LividJava"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17a85ebb5c9ed18a8270a371587cbc5403b62e48fbfc7098f69122fb027f2987"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0"
