name = "LividJava's Create Refabricated"
author = "LividJava"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d44cea6806d0592a723e8277096936fa41b7375c0cd0f342cb2c40f27179b8a"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"
