name = "LividJava's Create Refabricated"
author = "LividJava"
version = "testing"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1c081559b3c530e23b76a22d78ec4a759decaad46170f2ed7b4c95ffdda1e2f"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"
