name = "LividJava's Create Refabricated"
author = "LividJava"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "429a4a1ec9307c918b0d31f2cb1d67f35425f0003f0fe489218939a55f75c944"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"
