name = "LividJava's Create Re-Stitched"
author = "LividJava"
version = "1.0.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61b10324b6ac0a85e0b4ff70659cc2211af0b3f0331762e34fdd41ceb483bca3"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"
