name = "LividJava's Create Refabricated"
author = "LividJava"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2253ec665fa50f05867030096cef0cae7ed2467a25ab6fa6dc620015622bfae"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0"
