name = "LividJava's Create Re-Stitched"
author = "LividJava"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c24ef9ed5910577ad2a381a536f113e94bcd993c5d9ddedfc66595d4ae06edc"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0"
