name = "LividJava's Create Refabricated"
author = "LividJava"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7014c413d13d1f8c6614b0c0f93d91a8cb3bb95fbb09e1f30b0ab0d78598208b"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"
