name = "LividJava's Create Refabricated"
author = "LividJava"
version = "0.0.3-hotfix1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca49ba010afa25c8e70181a19ec1fa48264ff338d21c1b37b7267016356ddf32"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"
