name = "LividJava's Create Refabricated"
author = "LividJava"
version = "0.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "974005e906e962614c1a61af08253cc24dc2dff0e3297b948719822f0801cfbb"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"
