name = "LividJava's Create Re-Stitched"
author = "LividJava"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1569013273f2c2450e28b22391d0d77fe2aedfe79d43e4bea6d27678a2ae7df4"

[versions]
minecraft = "1.20.1"
quilt = "0.28.1"
