name = "LividJava's Create Refabricated"
author = "LividJava"
version = "0.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a02ca90b6744b2e76e00e1cad9b610c9e3347178bbafbed1eb9d93728e5f1861"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"
