// priority: 0
console.info('Good luck... this disables so many things')
ServerEvents.recipes(event => {
    // remove BetterX Items at runtime

	// BetterX Tools
	event.remove({output: 'betterend:aeternium_pickaxe'})
	event.remove({output: 'betterend:terminite_pickaxe'})
	event.remove({output: 'betterend:thallasium_pickaxe'})
	event.remove({output: 'betternether:cincinnasite_pickaxe'})
	event.remove({output: 'betternether:cincinnasite_pickaxe_diamond'})
	event.remove({output: 'betternether:flaming_ruby_pickaxe'})
	event.remove({output: 'betternether:nether_ruby_pickaxe'})
	event.remove({output: 'betterend:aeternium_axe'})
	event.remove({output: 'betterend:terminite_axe'})
	event.remove({output: 'betterend:thallasium_axe'})
	event.remove({output: 'betternether:cincinnasite_axe'})
	event.remove({output: 'betternether:cincinnasite_axe_diamond'})
	event.remove({output: 'betternether:flaming_ruby_axe'})
	event.remove({output: 'betternether:nether_ruby_axe'})
	event.remove({output: 'betterend:aeternium_sword'})
	event.remove({output: 'betterend:terminite_sword'})
	event.remove({output: 'betterend:thallasium_sword'})
	event.remove({output: 'betternether:cincinnasite_sword'})
	event.remove({output: 'betternether:cincinnasite_sword_diamond'})
	event.remove({output: 'betternether:flaming_ruby_sword'})
	event.remove({output: 'betternether:nether_ruby_sword'})
	event.remove({output: 'betterend:aeternium_shovel'})
	event.remove({output: 'betterend:terminite_shovel'})
	event.remove({output: 'betterend:thallasium_shovel'})
	event.remove({output: 'betternether:cincinnasite_shovel'})
	event.remove({output: 'betternether:cincinnasite_shovel_diamond'})
	event.remove({output: 'betternether:flaming_ruby_shovel'})
	event.remove({output: 'betternether:nether_ruby_shovel'})
	event.remove({output: 'betterend:aeternium_hoe'})
	event.remove({output: 'betterend:terminite_hoe'})
	event.remove({output: 'betterend:thallasium_hoe'})
	event.remove({output: 'betternether:cincinnasite_hoe'})
	event.remove({output: 'betternether:cincinnasite_hoe_diamond'})
	event.remove({output: 'betternether:flaming_ruby_hoe'})
	event.remove({output: 'betternether:nether_ruby_hoe'})
	// BetterX Armors
	event.remove({output: 'betterend:aeternium_helmet'})
	event.remove({output: 'betterend:crystalite_helmet'})
	event.remove({output: 'betterend:thallasium_helmet'})
	event.remove({output: 'betterend:terminite_helmet'})
	event.remove({output: 'betterend:aeternium_chestplate'})
	event.remove({output: 'betterend:crystalite_chestplate'})
	event.remove({output: 'betterend:thallasium_chestplate'})
	event.remove({output: 'betterend:terminite_chestplate'})
	event.remove({output: 'betterend:aeternium_leggings'})
	event.remove({output: 'betterend:crystalite_leggings'})
	event.remove({output: 'betterend:thallasium_leggings'})
	event.remove({output: 'betterend:terminite_leggings'})
	event.remove({output: 'betterend:aeternium_boots'})
	event.remove({output: 'betterend:crystalite_boots'})
	event.remove({output: 'betterend:thallasium_boots'})
	event.remove({output: 'betterend:terminite_boots'})
	event.remove({output: 'betternether:cincinnasite_helmet'})
	event.remove({output: 'betternether:nether_ruby_helmet'})
	event.remove({output: 'betternether:cincinnasite_chestplate'})
	event.remove({output: 'betternether:nether_ruby_chestplate'})
	event.remove({output: 'betternether:cincinnasite_leggings'})
	event.remove({output: 'betternether:nether_ruby_leggings'})
	event.remove({output: 'betternether:cincinnasite_boots'})
	event.remove({output: 'betternether:nether_ruby_boots'})
	event.remove({output: 'betternether:flaming_ruby_chestplate'})
	event.remove({output: 'betternether:flaming_ruby_leggings'})
	event.remove({output: 'betternether:flaming_ruby_helmet'})
	event.remove({output: 'betternether:flaming_ruby_boots'})

})


// TODO Add Disabled BetterX Items