console.log("Applying more Raccoon magic to blocks")
ServerEvents.tags('block', event => {
    event.add('create:wrench_pickup', 'toms_storage:ts.inventory_connector')
    event.add('create:wrench_pickup', 'toms_storage:ts.storage_terminal')
    event.add('create:wrench_pickup', 'toms_storage:ts.crafting_terminal')
    event.add('create:wrench_pickup', 'toms_storage:ts.trim')
    event.add('create:wrench_pickup', 'toms_storage:ts.open_crate')
    event.add('create:wrench_pickup', 'toms_storage:ts.inventory_cable')
    event.add('create:wrench_pickup', 'toms_storage:ts.inventory_cable_framed')
    event.add('create:wrench_pickup', 'toms_storage:ts.inventory_cable_connector')
    event.add('create:wrench_pickup', 'toms_storage:ts.inventory_cable_connector_framed')
    event.add('create:wrench_pickup', 'toms_storage:ts.inventory_cable_connector_filtered')
    event.add('create:wrench_pickup', 'toms_storage:ts.inventory_proxy')
    event.add('create:wrench_pickup', 'toms_storage:ts.level_emitter')
    event.add('create:wrench_pickup', 'toms_storage:ts.inventory_hopper_basic')
  })